-- Tested on SQL Azure 11 Oct 2016 

SELECT DATENAME(YEAR, GETDATE()) AS Year;
SELECT DATENAME(QUARTER, GETDATE()) AS Quarter;
SELECT DATENAME(MONTH, GETDATE()) AS Month;
SELECT DATENAME(WEEK, GETDATE()) AS Week;
SELECT DATENAME(WEEKDAY, GETDATE()) AS Weekday;
SELECT DATENAME(DAY, GETDATE()) AS Day;