-- Tested on SQL Azure 11 Oct 2016 

SELECT DATEPART(YEAR, GETDATE());
SELECT DATEPART(MONTH, GETDATE());
SELECT DATEPART(DAYOFYEAR, GETDATE());
SELECT DATEPART(ISO_WEEK, GETDATE());


SELECT DATEPART(TZoffset, TODATETIMEOFFSET(CAST(GETDATE() AS DATETIME2), '-07:00'));   --< Returns -420 which is -7 * 60 = -420
