USE tempdb;
GO


/* 

Creates a GUID that is greater than any GUID previously generated by this function on a specified computer since Windows was started. 
After restarting Windows, the GUID can start again from a lower range, but is still globally unique. When a GUID column is used as a 
row identifier, using NEWSEQUENTIALID can be faster than using the NEWID function. This is because the NEWID function causes random 
activity and uses fewer cached data pages. Using NEWSEQUENTIALID also helps to completely fill the data and index pages.

Source: https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(NEWSEQUENTIALID_TSQL);k(sql13.swb.tsqlresults.f1);k(sql13.swb.tsqlquery.f1);k(MiscellaneousFilesProject);k(DevLang-TSQL)&rd=true

*/

-- Tidy up from previous runs
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UniqueIdentifierExample]') AND type in (N'U'))
	DROP TABLE [dbo].[UniqueIdentifierExample]
GO



IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UniqueIdentifierExample]') AND type in (N'U'))
	DROP TABLE [dbo].[UniqueIdentifierExample]
GO

-- Now without the default
CREATE TABLE dbo.[UniqueIdentifierExample]
(
	Id				INT					IDENTITY(1, 1),
	UniqueColumn	UNIQUEIDENTIFIER	DEFAULT  NEWID()		--< GUIDs probably will not be in order
)
GO

INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;

-- GUIDs probably will not be in order
SELECT * FROM [UniqueIdentifierExample] ORDER BY Id;


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UniqueIdentifierExample]') AND type in (N'U'))
	DROP TABLE [dbo].[UniqueIdentifierExample]
GO

-- Now without the default
CREATE TABLE dbo.[UniqueIdentifierExample]
(
	Id				INT					IDENTITY,
	UniqueColumn	UNIQUEIDENTIFIER	DEFAULT  NEWSEQUENTIALID()	--< GUIDs will be in order
)
GO

INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;
INSERT dbo.[UniqueIdentifierExample] DEFAULT VALUES;

-- Now the GUIDs should be in order
SELECT * FROM [UniqueIdentifierExample] ORDER BY Id;


-- Tidy up

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UniqueIdentifierExample]') AND type in (N'U'))
	DROP TABLE [dbo].[UniqueIdentifierExample]
GO

